# Generated by Django 4.1 on 2022-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre Institución')),
                ('kind', models.CharField(max_length=56, verbose_name='Tipo de Institución')),
                ('area', models.CharField(max_length=56, verbose_name='Área a la que pertenece')),
                ('country', models.CharField(max_length=56, verbose_name='País')),
                ('website', models.CharField(max_length=56, verbose_name='Sitio Web')),
                ('description', models.CharField(max_length=256, verbose_name='Descripción de la Institución')),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
