# Generated by Django 4.1 on 2022-08-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la persona de contacto')),
                ('phone', models.BigIntegerField(default=0, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=120, verbose_name='Correo electrónico')),
            ],
            options={
                'db_table': 'contactpersons',
            },
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.CharField(max_length=120, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.contactperson', verbose_name='Persona de contacto'),
        ),
    ]
