# Generated by Django 4.1 on 2022-08-08 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_contactperson_alter_institution_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Institución a la que pertenece'),
            preserve_default=False,
        ),
    ]
