# Generated by Django 4.1 on 2022-08-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_remove_institution_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='institution',
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.contactperson', verbose_name='Persona de contacto'),
        ),
    ]
