# Generated by Django 4.1 on 2022-08-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del estudiante')),
                ('last_name', models.CharField(max_length=32, verbose_name='Apellido del estudiante')),
                ('email', models.EmailField(max_length=64)),
                ('address_street', models.CharField(max_length=32, verbose_name='Calle y número')),
                ('address_city', models.CharField(max_length=32, verbose_name='Ciudad')),
                ('address_state', models.CharField(max_length=32, verbose_name='Estado')),
                ('address_country', models.CharField(max_length=32, verbose_name='País')),
                ('zip_code', models.IntegerField(max_length=16)),
                ('degree', models.CharField(max_length=32, verbose_name='Nivel máximo de estudios')),
                ('area', models.CharField(max_length=32, verbose_name='Área de estudios')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
